### DISCUSSION TITLE
automation based on status change

### DISCUSSION THREAD

**Discussion by bertmelis** [astrandb/miele#222] [Q&A] [answered]
Hi,

I recently moved from https://github.com/HomeAssistant-Mods/home-assistant-miele to this integration but I have trouble adjusting the automation.

I just want to send a notice to my phone when the washing machine is finished. so I made an automation that is triggered by a change of the sensor `Washing machine Status` (`sensor.washing_machine_status_2`) from "Running" to "Program ended".

![image](https://user-images.githubusercontent.com/23474336/216564945-24c60102-541e-4d90-8903-695b7c32f646.png)

The notification works but it doesn't get triggered. This is, when I run it manually, I get a notification.

Did somebody do something similar?
How can I debug this?

**Comment by astrandb** [comment, marked as answer]
The to and from states should be the internal value strings. "Program ended" is a localized string. Try with `running` and `program_ended`.

**Reply by bertmelis** [reply]
I'll try that. I'm sure it will work, as @rudizl uses this too.
I assume I can find all the 'raw' states here: https://github.com/astrandb/miele/blob/main/custom_components/miele/const.py#L139

I'll do some laundry first before finally clicking to accept this answer 😄

**Reply by rudizl** [reply]
I think, that `from running` state is not needed.

**Reply by bertmelis** [reply]
I guess not. You can only end in "program_ended" when it was running before. But I assume it doesn't hurt to have it.

It's a relic from the other integration.

**Comment by rudizl** [comment]
This is mine and it`s working very well:

````
- id: "1637416801360"
  alias: Край пералня
  description: ""
  trigger:
    - platform: state
      entity_id:
        - sensor.washing_machine_status_2
      to: program_ended
      for:
        hours: 0
        minutes: 2
        seconds: 0
  condition: []
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.googlehome1449
        message: Програмата на пералнята приключи!
        language: bg
        cache: true
  mode: single
````
