### DISCUSSION TITLE
Sum up water / energy consumption in Homeassistant

### DISCUSSION THREAD

**Discussion by mldytech** [astrandb/miele#231] [Q&A] [answered]
I am currently using this integration with a miele washing machine. It successfully reports the water- and energy consumption throughout a washing cycle but resets the value to zero when the washing cycle ends.

Is there any way to create a sensor in homeassistant that logs the total water and energy consumption? Maybe someone already has a solution for this and could share it with me. 
Thank you!

![image](https://user-images.githubusercontent.com/61505510/222241219-384b5c4a-5750-4aa5-8131-8a8d1088f8f0.png)

**Comment by aturri** [comment, marked as answer]
Hi,
this is not possible as sensors rely on Miele API that is reporting the consumption based on the program currently running. This correctly maps on total increasing state class in Homeassistant (see https://developers.home-assistant.io/blog/2021/08/16/state_class_total/), so it's also possible to monitor water and energy consumption in the Energy dashboard.


In order to provide total water/energy consumption I have two input numbers that are updated by an automation at the end of the cycle:

```
trigger:
  - platform: state
    entity_id: sensor.washing_machine_status
    to: program_ended

condition:
  - condition: template
    value_template: "{{ trigger.from_state.state != 'not_connected' }}"
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unknown' }}"
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unavailable' }}"

action:
  - service: input_number.set_value
    data:
      value: >-
        {{ (states('sensor.washing_machine_energy_consumption')|float) +
        (states('input_number.washing_machine_total_energy_consumption')|float) }}
    target:
      entity_id: input_number.washing_machine_total_energy_consumption
  - service: input_number.set_value
    data:
      value: >-
        {{ (states('sensor.washing_machine_water_consumption')|float) +
        (states('input_number.washing_machine_total_water_consumption')|float) }}
    target:
      entity_id: input_number.washing_machine_total_water_consumption
```
