### DISCUSSION TITLE
Remote start of washing machine

### DISCUSSION THREAD

**Discussion by haaino** [astrandb/miele#259] [Q&A] [answered]
Hi,

Summer is coming and my solar panels start working again. 

I would like to start the washing machine when the solar power is at its highest. 

Is it possible to ...
1. Start the program of the washing machine remotely?
2. Set the correct program and start the washing machine?

Any help is appreciated. I've got a wwd660 setup and working in HA.

**Comment by aturri** [comment, marked as answer]
Hi,
I've implemented an automation that is able to start the machine when the cost of the energy is most convenient. Maybe you could do something similar.

The automation is triggered when pressing the "Start/Stop" button and when the price of energy changes:
```
trigger:
  - platform: state
    entity_id: sensor.washing_machine_status
    to: waiting_to_start
    from: programmed
  - platform: state
    entity_id: sensor.current_energy_cost
```

Automation is executed if all of the following conditions match:

- SmartStart feature is enabled on the machine (it can be activated in machine settings)
- MobileStart is off
- I have a boolean input to disable this feature from frontend of HA
- The "start at" sensor is not unknown (so machine has been programmed with delayed start)
- Current cost of energy is <= a threshold exposed by a template sensor

```
condition:
  - condition: state
    entity_id: binary_sensor.wahing_machine_smart_start
    state: "on"
  - condition: state
    entity_id: binary_sensor.wahing_machine_mobile_start
    state: "off"
  - condition: state
    entity_id: input_boolean.wahing_machine_enable_smart_start
    state: "on"
  - condition: not
    conditions:
      - condition: state
        state: unknown
        entity_id: sensor.washing_machine_start_at
  - condition: template
    value_template: >-
      {{ states('sensor.current_energy_cost') <= states('sensor.template_washing_machine_energy_price_threshold') }}
```

Action does the following:

- if the machine is off, it turns it on (probably this happens only on machines with M Touch display) and wait for the button to become unavailable
- press the start button

```
action:
  - if:
      - condition: state
        entity_id: sensor.washing_machine_status
        state: "off"
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.washing_machine_power_on
      - delay:
          hours: 0
          minutes: 0
          seconds: 20
          milliseconds: 0
  - if:
      - condition: state
        entity_id: button.washing_machine_start
        state: unavailable
    then:
      - delay:
          hours: 0
          minutes: 0
          seconds: 20
          milliseconds: 0
  - service: button.press
    data: {}
    target:
      entity_id: button.washing_machine_start
```

For calculating the value of `sensor.template_washing_machine_energy_price_threshold`, I have a template like this (under the assumption that I have sensors exposing the energy price for each hour range, such as `sensor.energy_hour_0`, `sensor.energy_hour_1`, etc.):
```
- unique_id: washing_machine
  sensor:
    - name: Washing Machine Energy Price Threshold
      unique_id: energy_price_threshold
      icon: mdi:currency-eur
      state: >
        {% set state_start_hour = states('sensor.washing_machine_start_at') %}
        {% if state_start_hour != 'unknown' and state_start_hour != 'unavailable' %}
        {% set start_hour = strptime(state_start_hour, '%H:%M').hour %}
        {% set cur_hour = now().hour %}
        {% set min_price = namespace(value=states('sensor.energy_hour_' + (cur_hour | string))) %}
        {% if start_hour > cur_hour %}
        {% for i in range(cur_hour,start_hour + 1) %}
        {% set i_price = states('sensor.energy_price_hour_' + (i | string)) %}
        {% if i_price < min_price.value %}
        {% set min_price.value = i_price %}
        {% endif %}
        {% endfor %}
        {% elif start_hour < cur_hour %}
        {% for i in range(cur_hour,24) %}
        {% set i_price = states('sensor.energy_price_hour_' + (i | string)) %}
        {% if i_price < min_price.value %}
        {% set min_price = i_price %}
        {% endif %}
        {% endfor %}
        {% for i in range(0,start_hour + 1) %}
        {% set i_price = states('sensor.energy_price_hour_' + (i | string)) %}
        {% if i_price < min_price.value %}
        {% set min_price.value = i_price %}
        {% endif %}
        {% endfor %}
        {% endif %}{{ min_price.value }}{% else %}unknown{% endif %}
```

You could do something similar with sensors reporting the forecast of solar energy production instead of energy price.
