### DISCUSSION TITLE
Localized Values in Automation

### DISCUSSION THREAD

**Discussion by Roemer** [astrandb/miele#307] [General]
Hello
I finally changed from the previous Integration to this integration. Thanks for the great work!
But there is one thing I could not easily get to run:
I have a script which tells me the washing machine state and the remaining time:
```
alias: Tell Washingmachine State
sequence:
  - service: tts.google_translate_say
    data_template:
      entity_id: media_player.esszimmer
      language: de
      message: >
        Die Waschmaschine ist {{states.sensor.washing_machine_status.state}}.
        Die Restdauer ist {{states.sensor.washing_machine_verbleibende_zeit.state | int // 60 }}
        Stunden und {{states.sensor.washing_machine_verbleibende_zeit.state | int % 60 }} Minuten.
mode: single
```
I adjusted it that it almost works. What is not working is that the `state` is the English value (eg. `running` here). But when looking at the value of the state in the UI, I get the localized value (`In Betrieb`). Is there a way to get this same localized value in the script without mapping it in the script itself?
