### DISCUSSION TITLE
Not sure how to construct automation

### DISCUSSION THREAD

**Discussion by RadianM** [astrandb/miele#412] [Q&A] [answered]
Having got the integration running and showing me the status of our dishwasher I wanted to create an automation to announce when the dishwasher finishes its program. The Program Phase entity: sensor.dishwasher_program_phase appears to have the appropriate "Finished" signal at the end of the process:

![Screenshot 2023-12-30 10 21 51](https://github.com/astrandb/miele/assets/13075243/f696c12d-936a-41b0-909e-731c2209c314)

So naively I constructed the following yaml:
```
alias: Dishes are done
description: ""
trigger:
  - entity_id:
      - sensor.dishwasher_program_phase
    platform: state
    to: Finished
condition: []
action:
  - service: notify.alexa_media
    data:
      data:
        type: announce
      message: The dishes are done.
      target:
        - media_player.everywhere
mode: single

```
However, the automation is never triggered and Traces reports "No traces found"

I arrived here in the discussions area while investigating the issue and note the possibility that the text "Finished" entered for the state change "To" might not be appropriate. Indeed, when constructing the automation using the graphical technique, the auto-suggested states for the "To" line do not seem to contain anything particularly useful:

![Screenshot 2023-12-30 10 37 16](https://github.com/astrandb/miele/assets/13075243/87af4a11-6ae6-4fef-bd61-6bf26ad58a34)

Other integrations I've used in automations mostly come up with sensible auto-suggestions for states so I suspect this is a big clue and I also note discussion about using raw values instead but this is where I hit a brick wall as I don't understand what this means. Perhaps someone would be kind enough to outline the typical steps involved in identifying the appropriate settings for achieving such an automation?
