### DISCUSSION TITLE
Unable to set program for my washing machine

### DISCUSSION THREAD

**Discussion by marcschumacher** [astrandb/miele#599] [Q&A]
I execute the following in Home Assistant:

```yaml
action: miele.set_program
data:
  programId: 24
  device_id: "00018613xxxx"
```

and get the following error: "Die Aktion miele.set_program konnte nicht ausgeführt werden. Failed to call service 'set_program'. Config entry for target not found.". I assume the specific device_id is not the right one. I took the same as I did in the Swagger UI, so I assume the number should be correct. (I redacted a part of the id BTW).

Can somebody help me about what I did wrong here?
