### ISSUE TITLE
HA Automation Entity state for Miele Washing Machine not being recognised

### ISSUE THREAD

**Issue by Daz42** [astrandb/miele#350]
### The problem

I am not entirely sure this is an issue with this integration but I have been asked to open an issue anyway. I have a Miele Washing Machine which is configured and appears to be working. I can turn the machine on and off and read the entity states. However, I have created an automation that sends a notification to my mobile phone when the entity sensor.washing_machine_status is 'finished'. However the automation never triggers (I can run it manually so the alert is being sent to my phone) despite the entity sensor.washing_machine_status showing 'finished'. Any help would one appreciated.

Also, I have a Miele Tumble Dryer also configured and an automation doing the same thing (not working).

I have a Gaggenau Dishwasher with the same automation which is working but using a different integration.

Any help would be appreciated.

### Version of miele integration having the issue?

0.1.16

### Version of Home Assistant Core having the issue?

2023.10.5

### Anything in the logs that might be useful for us?

```txt
I am seeing these in the logs:

Error requesting miele data: Cannot connect to host api.mcs3.miele.com:443 ssl:default [Try again]
```

**Comment by rudizl** [comment]
```
alias: End Washing machine
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.washing_machine_status_2
    to: program_ended
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - service: tts.google_say
    data:
      entity_id: media_player.googlehome1449
      message: Програмата на пералнята приключи!
      language: bg
      cache: true
mode: single
```
This is my automation and it works perfect.
