### ISSUE TITLE
Add sensor for Miele Autodos/PowerDisk

### ISSUE THREAD

**Issue by hajar97** [astrandb/miele#503]
### Feature request

I have a version of Miele dishwasher that has Autodos/PowerDisk container, using which you can start washing dishes immediately without having to add anything as it uses detergent from the Autodos compartment. 

Autodos periodically runs out and you have to refill it. When it happens I’d love to have an automation that sends me a notification so I wouldn’t forget to do it. If I do, I get to wash my dishes without any detergent and result is poor. 

In the app itself that information is definitely present and I suspect in the Cloud too. But HA integration doesn’t currently have a corresponding sensor. It would be really great if it could be added. 

![IMG_0834](https://github.com/astrandb/miele/assets/16057214/a5730da8-a3a2-4723-9a66-6f3ee719158a)

### What version of the integration are you using?

2024.5.0

**Comment by astrandb** [comment]
That info is not available in the public API. You could send your request to Miele to include the feature. However, they are usually not too responsive...

**Comment by hajar97** [comment]
I see. Do you know where I could send it to Miele?On 10 Jul 2024, at 09:03, Åke Strandberg ***@***.***> wrote:﻿
That info is not available in the public API. You could send your request to Miele to include the feature. However, they are usually not too responsive...

**Comment by astrandb** [comment]
Try developer@miele.com . Sometimes they answer, sometimes they don't.

**Comment by hajar97** [comment]
Thank you. Just sent them an email. I’ll post here in case they answer anything meaningful.

**Comment by zanoii** [comment]
> In the app itself that information is definitely present and I suspect in the Cloud too.

The screenshot says it's an estimate, so I wouldn't be surprised if they are just using the number of runs (and possibly program type of each run) to estimate the level of detergent remaining. If you don't get a reply on the API question (I wouldn't hold my breath..) you can easily achieve the same functionality in Home Assistant by setting up a helper.

**Comment by hajar97** [comment]
Yeah they never replied. So I guess your suggestion is good alternative. Why don’t we add it to the integration directly rather than have everyone set their own thing with helpers and counting number of runs, etc.?

**Comment by astrandb** [comment]
Stale issue - closing

**Comment by hajar97** [comment]
Just wanted to share with the community that this simple Automation in HA does indeed correctly detect when PowerDisk is empty and raises a notification. Hopefully will be useful to others. May be even useful to create a sensor despite the fact that Miele is not sharing it via the API yet:

```
alias: PowerDisk Notification
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.dishwasher_info
    to: "on"
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.dishwasher_program_phase
        state: not_running
      - condition: state
        entity_id: sensor.dishwasher_status
        state: programmed
    enabled: true
actions:
  - action: persistent_notification.create
    data:
      message: Replace Dishwasher's PowerDisk
      notification_id: dishwasher_powerdisk_empty
mode: single
```
