### ISSUE TITLE
ecoFeedback sensors

### ISSUE THREAD

**Issue by mundschenk-at** [astrandb/miele#74]
### Feature request

Some devices provide `ecoFeedback`, i.e. current power and water consumption, and maybe even a forecast for the whole program.

The data looks like this:

```json
      "ecoFeedback": {
        "currentWaterConsumption": {
          "unit": "l",
          "value": 0
        },
        "currentEnergyConsumption": {
          "unit": "kWh",
          "value": 0
        },
        "waterForecast": 0,
        "energyForecast": 0
      },
```

Here's the official [YAML schema for the API](https://www.miele.com/developer/swagger-ui/m3rdapi.yaml):
```yaml
        ecoFeedback:
          description: >-
            the `ecoFeedback` object returns the amount of water and energy used
            by the current running program up to the present moment. Furthermore
            it returns a forecast for water and energy consumption for a
            selected program.
          type: object
          properties:
            currentWaterConsumption:
              type: object
              properties:
                unit:
                  type: string
                  description: the measurement unit
                value:
                  type: number
                  description: the amount of water used
            currentEnergyConsumption:
              type: object
              properties:
                unit:
                  type: string
                  description: the measurement unit
                value:
                  type: number
                  description: the amount of energy used
            waterforecast:
              type: number
              description: the relative water usage for the selected program from 0 to 1
            energyforecast:
              type: number
              description: the relative energy usage for the selected program from 0 to 1
```

[According to the Miele developers](https://github.com/HomeAssistant-Mods/home-assistant-miele/issues/20#issuecomment-787485761) ([English translation](https://user-images.githubusercontent.com/5459845/109426993-9989f800-79f0-11eb-9186-340284dece15.png)), the `current*` keys might also contain data from a previous run when the appliance is in the `programmed` status. I would assume, the forecast percentage to mean that the currently `XX percent` of the expected maximum, i.e. to get to the forecast kWh from a `currentEnergyConsumption` of `0.5` and a `energyForecast` of `0.2`, you'd have to calculate `0.5 / 0.2` to arrive at `2.5`, but the examples given by Miele are not very clear in this regard.

### What version of the integration are you using?

miele-0.0.18
